### PR TITLE
Fix NPC Archon Crashes Server or Client with Charge Ball

### PR DESCRIPTION
**Pull request by ghost**
## Server-Side Crash
Due to respawn's weird native code, a NPC that is killed and gets cleaned( became ragdoll during death animation ) will pass the damage's inflictor as attacker
For ball lightning, the damage inflictor is the ball lightning mover, which can't use `GetOffhandWeapon()` method
**My Solution:** Adding `if ( attacker instanceof CBaseCombatCharacter )` check to indentify that attacker is a player or npc
### Video:
https://github.com/GalacticMoblin/Moblin.Archon/assets/56738369/03b29181-5993-471f-957e-964cc2651436

## Client-Side Crash
A mover( in this case is the ball lightning inflictor ) without valid owner can't be used to create a damage indicator, it will crash client-side
**My Solution:** Adding `DamageInfo_SetDamage( damageInfo, 0 )` when the attacker is not valid to avoid damage indicator shows up on client
### Video
https://github.com/GalacticMoblin/Moblin.Archon/assets/56738369/d41fd43c-7b29-40d0-9a32-10c3c2a3a7a8

## Fixed Video
https://github.com/GalacticMoblin/Moblin.Archon/assets/56738369/af65a873-ab67-4228-bec7-64aace21f290

Might look a little bit weird since the arcball no longer does any damage. Maybe just remove them when this happens?

### CODE REVIEW

**Comment by Dinorush** [comment]
I don't think this is the best way to go about fixing it. There's no reason the arcballs shouldn't do damage after their owner dies. Given that the breaking portion of the code is `attacker.GetOffhandWeapon(OFFHAND_RIGHT)` as far as I can tell, the best fix is adding a check before with
```c++
if ( attacker.IsProjectile() )
    return
```
Edit: Missed the client crash, will look a bit further into that one.
Edit2: Found a workaround to fix both. Should use:
```c++
if ( attacker.IsProjectile() )
{
    DamageInfo_AddCustomDamageType( damageInfo, DF_NO_INDICATOR )
    return
}
```
This prevents the crashing function from generating indicators for the damage. (I did not test this, just read the code)

**Comment by DBmaoha** [comment]
> I don't think this is the best way to go about fixing it. There's no reason the arcballs shouldn't do damage after their owner dies. Given that the breaking portion of the code is `attacker.GetOffhandWeapon(OFFHAND_RIGHT)` as far as I can tell, the best fix is adding a check before with
> 
> ```c++
> if ( attacker.IsProjectile() )
>     return
> ```
> 
> Edit: Missed the client crash, will look a bit further into that one. Edit2: Found a workaround to fix both. Should use:
> 
> ```c++
> if ( attacker.IsProjectile() )
> {
>     DamageInfo_AddCustomDamageType( damageInfo, DF_NO_INDICATOR )
>     return
> }
> ```
> 
> This prevents the crashing function from generating indicators for the damage. (I did not test this, just read the code)

I'll implement these changes and have a test

**Comment by ghost** [comment]
> I don't think this is the best way to go about fixing it. There's no reason the arcballs shouldn't do damage after their owner dies. Given that the breaking portion of the code is `attacker.GetOffhandWeapon(OFFHAND_RIGHT)` as far as I can tell, the best fix is adding a check before with
> 
> ```c++
> if ( attacker.IsProjectile() )
>     return
> ```
> 
> Edit: Missed the client crash, will look a bit further into that one. Edit2: Found a workaround to fix both. Should use:
> 
> ```c++
> if ( attacker.IsProjectile() )
> {
>     DamageInfo_AddCustomDamageType( damageInfo, DF_NO_INDICATOR )
>     return
> }
> ```
> 
> This prevents the crashing function from generating indicators for the damage. (I did not test this, just read the code)

The arcball's lightning damage uses mover as inflictor, so after owner gets destroyed, the attacker will be the mover but not the projectile itself( thanks to respawn's code ). Use `if ( attacker.IsProjectile() )` can't handle it, that's why I chose to use `if ( !( attacker instanceof CBaseCombatCharacter ) )`( `if ( !attacker.IsPlayer() && !attacker.IsNPC() )` can handle it too )

I'll have a test on adding `DF_NO_INDICATOR` to damage flags

**Comment by ghost** [comment]
`DamageInfo_AddCustomDamageType( damageInfo, DF_NO_INDICATOR )` works fine!
EDIT: Still needs testing, I forgot to disable my mod that modified `_ball_lightning.gnut` to make projectile itself as lightning attacker
EDIT2: Yes it works, after removing my mod and adding `DF_NO_INDICATOR`, the arcball lightning won't crash client anymore and it can still deal damage
image

**Comment by ghost** [comment]
Fixed Video

https://github.com/GalacticMoblin/Moblin.Archon/assets/56738369/bb02ba63-b3fb-4700-beb4-f4914ebe462b

**Comment by GalacticMoblin** [comment]
Will review the PR at some point soon(ish)

**Pull request merged**
